-- Enforce NOT NULL on tenantId for core models (after backfill)
BEGIN;

ALTER TABLE "User" ALTER COLUMN "tenantId" SET NOT NULL;
ALTER TABLE "Account" ALTER COLUMN "tenantId" SET NOT NULL;
ALTER TABLE "Contact" ALTER COLUMN "tenantId" SET NOT NULL;
ALTER TABLE "Lead" ALTER COLUMN "tenantId" SET NOT NULL;
ALTER TABLE "Opportunity" ALTER COLUMN "tenantId" SET NOT NULL;
ALTER TABLE "Activity" ALTER COLUMN "tenantId" SET NOT NULL;
ALTER TABLE "Note" ALTER COLUMN "tenantId" SET NOT NULL;
ALTER TABLE "QuoteItem" ALTER COLUMN "tenantId" SET NOT NULL;
ALTER TABLE "QuoteApproval" ALTER COLUMN "tenantId" SET NOT NULL;
ALTER TABLE "Contract" ALTER COLUMN "tenantId" SET NOT NULL;
ALTER TABLE "ContractApproval" ALTER COLUMN "tenantId" SET NOT NULL;
ALTER TABLE "ContractSignatureRequest" ALTER COLUMN "tenantId" SET NOT NULL;
ALTER TABLE "ContractAuditLog" ALTER COLUMN "tenantId" SET NOT NULL;
ALTER TABLE "ContractVersion" ALTER COLUMN "tenantId" SET NOT NULL;
ALTER TABLE "Document" ALTER COLUMN "tenantId" SET NOT NULL;
ALTER TABLE "ERPOrder" ALTER COLUMN "tenantId" SET NOT NULL;
ALTER TABLE "Invoice" ALTER COLUMN "tenantId" SET NOT NULL;
ALTER TABLE "PaymentTransaction" ALTER COLUMN "tenantId" SET NOT NULL;
ALTER TABLE "Subscription" ALTER COLUMN "tenantId" SET NOT NULL;
ALTER TABLE "Payment" ALTER COLUMN "tenantId" SET NOT NULL;

COMMIT;
